### ISSUE TITLE
Front Camera

### ISSUE THREAD

**Issue by rajeshsws** [Scandit/datacapture-dotnet-samples#1]
Hi
How by default we can open Front Camera. My Application using front camera as operator is fixed and devices id fixed in front of  him to scan the qr code. and how we can open in POP window with this scanned IT Api.
I am using .Net maui Blazor app.

**Comment by ScanditSupport** [comment]
Hi @rajeshsws,

My apologies, could you please clarify, do you mean the popup view?
https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/views/popup

Generally speaking, the dataCaptureView inherits from the `relativeLayout`/`Layout<View>`, so it has the same limitations 
https://docs.scandit.com/data-capture-sdk/dotnet.android/core/api/ui/data-capture-view.html#class-Scandit.DataCapture.Core.UI.DataCaptureView
https://docs.scandit.com/data-capture-sdk/xamarin.forms/core/api/ui/data-capture-view.html#class-Scandit.DataCapture.Core.UI.DataCaptureView

In case you have more detailed questions, please feel free to reach out to us directly: [Submit a request – Frequently Asked Questions (FAQ)](https://support.scandit.com/hc/en-us/requests/new)

**Comment by rajeshsws** [comment]
Dear Scandit/datacapture-dotnet-samples
Please check the photo and understand my requirement and let me know how i
can do that.
[image: image.png]
Thank you
Best Regards
Rajesh Shoky (9716000503)
Methods Apparel Consultancy India Pvt Ltd.
Vipul Business Park
Suite :1016, 10th floor
Sector 48
Gurugram-122001
Skype ID : shoky114
Linked In :LinkedIn.com/in/rajeshsheokand
what's App :+919716000503

**Comment by ScanditSupport** [comment]
Hi @rajeshsws,

I am afraid that no photo was attached.
Can you please reach out to us directly and share the photo alongside with a few snippets of your code on how you implemented Scandit? [Submit a request – Frequently Asked Questions (FAQ)](https://support.scandit.com/hc/en-us/requests/new)

**Comment by rajeshsws** [comment]
Please check your email I sent directly on the link you provided.
Thank you
Best Regards
Rajesh Shoky (9716000503)
Methods Apparel Consultancy India Pvt Ltd.
Vipul Business Park
Suite :1016, 10th floor
Sector 48
Gurugram-122001
Skype ID : shoky114
Linked In :LinkedIn.com/in/rajeshsheokand
what's App :+919716000503
