### ISSUE TITLE
.net maui Blazor app and need to scan qr code with front camera

### ISSUE THREAD

**Issue by rajeshsws** [Scandit/datacapture-dotnet-samples#2]
![issue](https://github.com/Scandit/datacapture-dotnet-samples/assets/48245007/49160555-b272-4d32-a445-fd0e08fecce6)

Please read above my requirements. 
User will click on Scan Now button. Modal pop window will open in Xaml page read the qr code and close and return QR code ID.
My app is made in .NET MAUI Blazor which has android, IOS and window system.
I have seen your API which supporting only android and iOS when i have window platform there its giving error and not able to compile. code.
Please suggest solutions ASAP . once this issue is resolved will integrate API in my project
Thank you very much.

**Comment by ScanditSupport** [comment]
Hi [@rajeshsws](https://github.com/rajeshsws),

We do not support Windows through .NET MAUI.

Can you please reach out to us directly and share a few snippets of you code on how you implemented Scandit so we can better understand your use case?

[Submit a request – Frequently Asked Questions (FAQ)](https://support.scandit.com/hc/en-us/requests/new)

**Comment by rajeshsws** [comment]
.met MAUI Blazor page call xaml scanner page
![image](https://github.com/Scandit/datacapture-dotnet-samples/assets/48245007/ee2802a8-d5ea-4be6-af7c-9383afb9d8d2)

XAML Page
![image](https://github.com/Scandit/datacapture-dotnet-samples/assets/48245007/d7417273-852a-4793-8fd7-fc3f5e10d10e)

![image](https://github.com/Scandit/datacapture-dotnet-samples/assets/48245007/701e0651-b3a9-4c91-bafe-3f7bb3e1b48a)


I want Scan qr code and close come back to again blazor page.
Right now scanning is working properly but not able to close window and come back to blazor page.
Other thing is i want blazor page code shoudl await unless scanner page return barcode id so that i can execute somthing after getting barcode ID.
I want to open your scanner XAML page in modal POP up xaml  page because modal pop xaml page return value on close.
Thank you

**Comment by rajeshsws** [comment]
Right now I am using Zxing.net.maui scanner app to scan. But i feel that is bit slow. that why i am looking your app.
![image](https://github.com/Scandit/datacapture-dotnet-samples/assets/48245007/8fcf84a8-edec-407f-b4c2-c608226e1760)
on click yellow button xaml modal pop up xaml page is iopening and scanning qr code with front camera and closing and returing qr code id.
Hope this will help you to understand it
